# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-19 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='requestor',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='target',
            new_name='email2',
        ),
    ]
