# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0003_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='blockedlist',
            unique_together=set([('requestor', 'target')]),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('email1', 'email2')]),
        ),
        migrations.AlterUniqueTogether(
            name='subscribelist',
            unique_together=set([('requestor', 'target')]),
        ),
    ]
